//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicturePDF {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExtraStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtraStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicturePDF.ExtraStrings", typeof(ExtraStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A0.
        /// </summary>
        internal static string paperSize_A0 {
            get {
                return ResourceManager.GetString("paperSize.A0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1.
        /// </summary>
        internal static string paperSize_A1 {
            get {
                return ResourceManager.GetString("paperSize.A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2.
        /// </summary>
        internal static string paperSize_A2 {
            get {
                return ResourceManager.GetString("paperSize.A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A3.
        /// </summary>
        internal static string paperSize_A3 {
            get {
                return ResourceManager.GetString("paperSize.A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        internal static string paperSize_A4 {
            get {
                return ResourceManager.GetString("paperSize.A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A5.
        /// </summary>
        internal static string paperSize_A5 {
            get {
                return ResourceManager.GetString("paperSize.A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A6.
        /// </summary>
        internal static string paperSize_A6 {
            get {
                return ResourceManager.GetString("paperSize.A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        internal static string paperSize_Custom {
            get {
                return ResourceManager.GetString("paperSize.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledger.
        /// </summary>
        internal static string paperSize_Ledger {
            get {
                return ResourceManager.GetString("paperSize.Ledger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string paperSize_Legal {
            get {
                return ResourceManager.GetString("paperSize.Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        internal static string paperSize_Letter {
            get {
                return ResourceManager.GetString("paperSize.Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabloid.
        /// </summary>
        internal static string paperSize_Tabloid {
            get {
                return ResourceManager.GetString("paperSize.Tabloid", resourceCulture);
            }
        }
    }
}
